// <auto-generated />
namespace WiredExamApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adddatetimecolumntoexamtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddatetimecolumntoexamtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712242149557_Add datetime column to exam table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
